version: "3.7"

services:
  sqlserver:
    image: tobiasfenster/mssql-server-exp-unsupported:2019-cu11
    container_name: mssql
    ports:
      - "1438:1433"
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=P@55w0rd"