// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ExampleProtoInt2.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ReportService {

  /// <summary>Holder for reflection information generated from ExampleProtoInt2.proto</summary>
  public static partial class ExampleProtoInt2Reflection {

    #region Descriptor
    /// <summary>File descriptor for ExampleProtoInt2.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExampleProtoInt2Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZFeGFtcGxlUHJvdG9JbnQyLnByb3RvEg1SZXBvcnRTZXJ2aWNlIjkKEFRl",
            "c3RpbmdQcm90b0ludDISEwoLQ29sdW1uQ291bnQYASADKAUSEAoIUm93Q291",
            "bnQYAiADKAViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ReportService.TestingProtoInt2), global::ReportService.TestingProtoInt2.Parser, new[]{ "ColumnCount", "RowCount" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TestingProtoInt2 : pb::IMessage<TestingProtoInt2> {
    private static readonly pb::MessageParser<TestingProtoInt2> _parser = new pb::MessageParser<TestingProtoInt2>(() => new TestingProtoInt2());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TestingProtoInt2> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReportService.ExampleProtoInt2Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestingProtoInt2() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestingProtoInt2(TestingProtoInt2 other) : this() {
      columnCount_ = other.columnCount_.Clone();
      rowCount_ = other.rowCount_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestingProtoInt2 Clone() {
      return new TestingProtoInt2(this);
    }

    /// <summary>Field number for the "ColumnCount" field.</summary>
    public const int ColumnCountFieldNumber = 1;
    private static readonly pb::FieldCodec<int> _repeated_columnCount_codec
        = pb::FieldCodec.ForInt32(10);
    private readonly pbc::RepeatedField<int> columnCount_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> ColumnCount {
      get { return columnCount_; }
    }

    /// <summary>Field number for the "RowCount" field.</summary>
    public const int RowCountFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_rowCount_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> rowCount_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> RowCount {
      get { return rowCount_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TestingProtoInt2);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TestingProtoInt2 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!columnCount_.Equals(other.columnCount_)) return false;
      if(!rowCount_.Equals(other.rowCount_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= columnCount_.GetHashCode();
      hash ^= rowCount_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      columnCount_.WriteTo(output, _repeated_columnCount_codec);
      rowCount_.WriteTo(output, _repeated_rowCount_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += columnCount_.CalculateSize(_repeated_columnCount_codec);
      size += rowCount_.CalculateSize(_repeated_rowCount_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TestingProtoInt2 other) {
      if (other == null) {
        return;
      }
      columnCount_.Add(other.columnCount_);
      rowCount_.Add(other.rowCount_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            columnCount_.AddEntriesFrom(input, _repeated_columnCount_codec);
            break;
          }
          case 18:
          case 16: {
            rowCount_.AddEntriesFrom(input, _repeated_rowCount_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
