name: build
on:
  push:
    branches:
      - "*"

jobs:
  build-n-test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: dotnet build
    - run: docker-compose -f ./ReportService.Tests/docker-compose.yml up -d
    - run: dotnet test